services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ".env"
    ports:
      - 3000:3000

  db:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - db-data/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: freelance_app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - db-data/pgadmin_data:/var/lib/pgadmin
volumes:
  - db-data
