services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        UPLOADTHING_SECRET: ${UPLOADTHING_SECRET}
        UPLOADTHING_APP_ID: ${UPLOADTHING_APP_ID}
        WEBHOOK_SECRET: ${WEBHOOK_SECRET}
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
        NEXT_PUBLIC_CHAT_SERVER_URL: ${NEXT_PUBLIC_CHAT_SERVER_URL}}
        NEXT_PUBLIC_ADMIN_USER_ID: ${NEXT_PUBLIC_ADMIN_USER_ID}}
        NEXT_PUBLIC_ADMIN_WALLET_ID: ${NEXT_PUBLIC_ADMIN_WALLET_ID}}
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - UPLOADTHING_SECRET=${UPLOADTHING_SECRET}
      - UPLOADTHING_APP_ID=${UPLOADTHING_APP_ID}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
      - NEXT_PUBLIC_CHAT_SERVER_URL=${NEXT_PUBLIC_CHAT_SERVER_URL}
      - NEXT_PUBLIC_ADMIN_USER_ID=${NEXT_PUBLIC_ADMIN_USER_ID}
      - NEXT_PUBLIC_ADMIN_WALLET_ID=${NEXT_PUBLIC_ADMIN_WALLET_ID}
    env_file: ".env.prod"
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - node_modules:/app/node_modules
      - .:/app

  db:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
    volumes:
      - db-data:/pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
  node_modules:

networks:
  default:
    name: freelance_network
