FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY prisma ./prisma/

COPY . .

RUN npx prisma generate

# Define build-time arguments for environment variables
ARG DATABASE_URL
ARG GITHUB_CLIENT_ID
ARG GITHUB_CLIENT_SECRET
ARG GOOGLE_ID
ARG GOOGLE_SECRET
ARG UPLOADTHING_SECRET
ARG UPLOADTHING_APP_ID
ARG NEXT_PUBLIC_BASE_URL

# Set environment variables that will persist in the final image
ENV DATABASE_URL=$DATABASE_URL
ENV GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID
ENV GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET
ENV GOOGLE_ID=$GOOGLE_ID
ENV GOOGLE_SECRET=$GOOGLE_SECRET
ENV UPLOADTHING_SECRET=$UPLOADTHING_SECRET
ENV UPLOADTHING_APP_ID=$UPLOADTHING_APP_ID
ENV NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL

RUN npm run build

EXPOSE 3000

CMD [ "npm", "run", "start" ]