name: Build Freelance Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/freelance-hub-web:latest
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            UPLOADTHING_SECRET=${{ secrets.UPLOADTHING_SECRET }}
            UPLOADTHING_APP_ID=${{ secrets.UPLOADTHING_APP_ID }}
            WEBHOOK_SECRET=${{ secrets.WEBHOOK_SECRET }}
            NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }}
            NEXT_PUBLIC_CHAT_SERVER_URL=${{ secrets.NEXT_PUBLIC_CHAT_SERVER_URL }}
            NEXT_PUBLIC_ADMIN_USER_ID=${{ secrets.NEXT_PUBLIC_ADMIN_USER_ID }}
            NEXT_PUBLIC_ADMIN_WALLET_ID=${{ secrets.NEXT_PUBLIC_ADMIN_WALLET_ID }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.prod.yaml,scripts/deploy.sh"
          target: "/home/ubuntu/freelance-hub"
          strip_components: 0

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/freelance-hub
            export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            chmod +x scripts/deploy.sh
            ./scripts/deploy.sh
